spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: social-media
          uri: lb://social-media
          predicates:
            - Path=/social-media/**
          filters:
            - RewritePath=/social-media/(?<segment>.*), /$\{segment}
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
server:
  port: 9000

eureka:
  instance:
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: ${EUREKA_ADDRESS}/eureka/
