spring:
  flyway:
    schemas: social_media
  application:
    name: social-media
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      default_schema: social_media
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

server:
  port: 3000