spring:
  application:
    name: keycloak-gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: social-media
          uri: http://127.0.0.1:3000
          predicates:
            - Path=/social-media/**
          filters:
            - RemoveRequestHeader=Cookie
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ADDRESS}/realms/${KEYCLOAK_REALM_NAME}
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_NAME}
            client-secret: ${KEYCLOAK_SECRET}
            authorization-grant-type: authorization_code
            scope: openid
            auth-uri: ${KEYCLOAK_ADDRESS}
            realm: ${KEYCLOAK_REALM_NAME}

server:
  port: 9000
eureka:
  instance:
    hostname: localhost
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: ${EUREKA_ADDRESS}/eureka/

logging:
  level:
    org:
      springframework:
        security: DEBUG
