spring:
  flyway:
    schemas: auth
  application:
    name: keycloak-gateway
  datasource:
    url: jdbc:postgresql://${POSTGRES_ADDRESS}/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      default_schema: auth
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ADDRESS}/realms/${KEYCLOAK_REALM_NAME}
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_NAME}
            client-secret: ${KEYCLOAK_SECRET}
            authorization-grant-type: authorization_code
            scope: openid
            auth-uri: ${KEYCLOAK_ADDRESS}
            realm: ${KEYCLOAK_REALM_NAME}

server:
  port: 9000
eureka:
  instance:
    hostname: localhost
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: ${EUREKA_ADDRESS}/eureka/

logging:
  level:
    org:
      springframework:
        security: DEBUG
